const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const menuSchema = new Schema({
	date: { type: Date, required: true },
	// logo: { type: String, required: false },
	// image: { type: String, required: false },
	// contact: { type: String, required: true },
	introduction: { type: String, required: true },
	promotion: { type: String, required: false },
	// instruction: { type: String, required: true },
	// prices: [String],
	monday: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	tuesday: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	wednesday: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	thursday: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	friday: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	frozen: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			side: { type: String, required: false },
			sidename: { type: String, required: false },
			sidedescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	vegies: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	salads: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	soups: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	sides: [
		{
			image: { type: String, required: false },
			main: { type: String, required: false },
			mainname: { type: String, required: false },
			maindescription: { type: String, required: false },
			count: { type: Number, required: true },
			cost: { type: Number, multipleOf: 0.01, required: true },
			price: { type: Number, multipleOf: 0.01, required: true },
		},
	],
	// note: { type: String, required: true },
});

module.exports = mongoose.model("Menu", menuSchema);
